name: Dynamic Template

on:
  push:
    branches:
      - main
    paths:
      - 'README.md'
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update_templates:
    name: "Update Markdown Templates"
    runs-on: ubuntu-latest
    steps:
      - name: "📥  Fetching Repository Contents"
        uses: actions/checkout@main

      - name: "💾  Github Repository Metadata"
        uses: varunsridharan/action-repository-meta@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: "💫  Dynamic Template Render"
        uses: varunsridharan/action-dynamic-readme@main
        with:
          GLOBAL_TEMPLATE_REPOSITORY: CraftyServerMC/resources/templates/dynamic-readme-templates
          files: |
            README.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}